/**
 * Reads .env and generates config.js for the browser.
 * Run: node build-env.js
 */
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('ERROR: .env file not found. Copy .env.example to .env and fill in your keys.');
  process.exit(1);
}

const env = {};
fs.readFileSync(envPath, 'utf-8')
  .split('\n')
  .filter(line => line.trim() && !line.startsWith('#'))
  .forEach(line => {
    const [key, ...rest] = line.split('=');
    env[key.trim()] = rest.join('=').trim();
  });

const required = ['RAZORPAY_KEY_ID', 'FORMSPREE_FORM_ID', 'CREATE_ORDER_URL', 'VERIFY_PAYMENT_URL'];
const missing = required.filter(k => !(k in env));
if (missing.length) {
  console.warn(`WARNING: Missing keys in .env: ${missing.join(', ')}`);
}

const config = `// Auto-generated by build-env.js — do NOT edit or commit this file.
window.__CONFIG = ${JSON.stringify(env, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), config);
console.log('✓ config.js generated from .env');
