// Auto-generated by build-env.js — do NOT edit or commit this file.
// NOTE: Only the PUBLIC Razorpay key is safe in the browser. Secret key is backend-only.
window.__CONFIG = {
  "RAZORPAY_KEY_ID": "rzp_live_Su3NM8aUmxQqfG"
};